# Site settings
title: In Reveries of Mania 
email: manicdesigner@gmail.com
description: >
  In Reveries of Mania. Is a mental health page, focused primarily on Bipolar, A.D.D and A.D.H.D. As I create there will be pages and posts about what I have encountered, views, and any info I can pass to others. 

baseurl: "/mental-health" # the subpath of your site, e.g. /blog/
url: https://mikeyhavoc.github.io/mental-health # the base hostname & protocol for your site
git_address: https://github.com/mikeyhavoc/mental-health.git
git_edit_address: https://github.com/mikeyhavoc/mental-health/blob/gh-pages

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
