# Site settings
title: Creative Concious Healing
email: manicdesigner@gmail.com
description: Creative Concious Healing Center blog and originating site. For an upcoming Mental Health goal in Bradenton FL. 

baseurl: "/mental-health" # the subpath of your site, e.g. /blog/
url: https://mikeyhavoc.github.io/mental-health # the base hostname & protocol for your site
git_address: https://github.com/mikeyhavoc/mental-health.git
git_edit_address: https://github.com/mikeyhavoc/mental-health/blob/gh-pages

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: sandstone

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
# disqus comments
disqus:
    # leave shortname blank to disable comments site-wide
    # disable comments for any post by adding 'comments: false' 
    # to that YAML Front Matter.
    shortname: disqus_mikeyhavoc